input_size: [256, 256]
input_channel: 3

depth_multiple: 1
width_multiple: 1

anchors: &anchors
   - [10,13, 16,30, 33,23]  # P3/8
   - [30,61, 62,45, 59,119]  # P4
   - [116,90, 156,198, 373,326]  # P5/32

n_classes: &n_classes
  80

activation: &activation
  SiLU

backbone:
    # [from, repeat, module, args]
    [
        [-1, 1, Conv, [32, 3, 2], {activation: *activation}],
        [-1, 1, MV2Block, [64, 1, 4], {activation: *activation}],
        [-1, 1, MV2Block, [96, 2, 4], {activation: *activation}],
        [-1, 2, MV2Block, [96, 1, 4], {activation: *activation}],
        [-1, 1, MV2Block, [128, 2, 4], {activation: *activation}],
        # MobileViTBlock (Conv channel, MLP channel, depth)
        [-1, 1, MobileViTBlock, [288, 576, 2], {activation: *activation}],  # 5
          
        [-1, 1, MV2Block, [256, 2, 4], {activation: *activation}],
        [-1, 1, MobileViTBlock, [240, 960, 4], {activation: *activation}],  # 7

        [-1, 1, MV2Block, [320, 2, 4], {activation: *activation}],
        [-1, 1, MobileViTBlock, [384, 1280, 3], {activation: *activation}],  # 9

        # Neck
        [-1, 1, Conv, [256, 1, 1], {activation: *activation}],
        [-1, 1, UpSample, [null, 2]],
        [[-1, 7], 1, Concat, [1]],
        [-1, 3, C3, [256, False], {activation: *activation}],  # 13

        [-1, 1, Conv, [128, 1, 1], {activation: *activation}],
        [-1, 1, UpSample, [null, 2]],
        [[-1, 5], 1, Concat, [1]], 
        [-1, 3, C3, [128, False], {activation: *activation}],  # 17

        [-1, 1, Conv, [128, 3, 2], {activation: *activation}],
        [[-1, 14], 1, Concat, [1]],
        [-1, 3, C3, [256, False], {activation: *activation}],  # 20
        
        [-1, 1, Conv, [256, 3, 2], {activation: *activation}],
        [[-1, 10], 1, Concat, [1]],
        [-1, 3, C3, [512, False], {activation: *activation}]  # 23
    ]

head:
  [
    [[17, 20, 23], 1, YOLOHead, [*n_classes, *anchors]]
  ]
