# TTA 1
scales:
  - 1
  - 0.83
  - 0.67

flips:
  - null
  - 3  # flips (2-ud, 3-lr)
  - null

# # TTA 2
# scales:
#   - 1
#   - 0.83
#   - 0.67

# flips:
#   - null
#   - 3
#   - 3

# # TTA 3
# scales:
#   - 1
#   - 0.83
#   - 0.67
#   - 0.52

# flips:
#   - null
#   - 3
#   - null
#   - 3

# # TTA 4
# scales:
#   - 1
#   - 0.83
#   - 0.67
#   - 0.52

# flips:
#   - null
#   - 3
#   - 3
#   - 3

# # TTA 5
# scales:
#   - 1
#   - 0.83
#   - 0.67
#   - 0.52
#   - 0.38

# flips:
#   - null
#   - 3
#   - 3
#   - 3
#   - 3
