img_width:  # image width search space with categorical
  low: 512
  high: 768
  step: 32

iou_thr:  # iou threshold search space
  low: 0.
  high: 1.

conf_thr:  # confidence threshold search space
  low: 0.
  high: 1.
