model:
  name: yolov5x
  weights: weights/yolov5x.pt
  stride_size: 32
  n_param: 86705005
  wandb: j-marple/AYolov2/1gxaqgk4
  half: False

inference:
  batch_size: 8
  conf_t: 0.001
  iou_t: 0.65
  nms_box: 3000
  agnostic: True 

data:
  # path: /home/agc2021/dataset
  path: /mnt/ssd/datasets/coco/images/val2017
  img_size: 832
  rect: True
  use_mp: False
  pad: 0.5
  
